services:
  db:
    image: postgres:15
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 32mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    
  meshtastic:
    build: .
    container_name: mesh
    volumes:
      - ./watch.txt:/app/watch.txt
    environment:
      - DBNAME=meshtastic
      - DBHOST=10.1.100.252
      - DBUSER=postgres
      - DBPASS=example
      - DBPORT=5432
      - LOGGING=debug
      - EPASSWORD=password
      - ESENDER=wlg915alerts@gmail.com
